### ISSUE TITLE
R4 Missing from BOM

### ISSUE THREAD

**Issue by SwitchGB** [InsaneDruid/CBM-D9096#2]
R4 is missing off the BOM :)

**Comment by InsaneDruid** [comment]
That's by design as it needs to be a jumper when using bidirectional dual LED for PWR/ERROR (like on the disk drives). Thus its marked _don't install_ in the schematics. It his, however, referenced as "R2" in the Text describing the setup for 3 discrete LED :)

I have a think to mark it clearer in the BOM, too

**Comment by InsaneDruid** [comment]
fixed schematics text and added readme sections
